DB課題２の提出です
shiraosa/quelcode-db pull request #3
Opened 2020-07-10 06:45 UTC by shiraosa

やったこと

- データベース定義書とDDL文(init.sql)の作成

- DDL文の動作確認

レビューよろしくお願いします

2020-07-10 07:35 UTC, piasoratech requested changes
全体を通して外部キーが全く設定されていないので、その部分も確認して修正してください。

2020-07-10 07:35 UTC, piasoratech commented on db/db-challenge2/init.sql
> +    `file` VARCHAR(100),
この名前だとファイルそのものなのかファイル名なのかよくわからないので見直してください。

2020-07-10 07:35 UTC, piasoratech commented on db/db-challenge2/init.sql
> +    `is_attache_file` TINYINT(1) DEFAULT 0 NOT NULL,
typoしてますね

2020-07-10 08:06 UTC, shiraosa commented
以下を修正しました

- タイプミス

- 物理名fileをfile_nameに変更しました

- 外部キーの設定をしました。

2020-07-10 08:38 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-07-10 08:38 UTC, piasoratech commented on db/db-challenge2/init.sql
> +    `is_attached_file` TINYINT(1) DEFAULT 0 NOT NULL,
この名前だと本来の「ファイル送信が許可されているかどうか」が分からないので、命名を考えましょう。
また、デフォルト値は指定されているので、要件も確認してください。

2020-07-13 01:50 UTC, shiraosa commented
以下を修正しました

- 物理名`is_attached_file`を`is_unsendable_file`に修正しました。

- ファイル送信制御フラグのデフォルトを送信許可に修正しました。

2020-07-13 02:24 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-07-13 02:24 UTC, piasoratech commented on db/db-challenge2/init.sql
> +    `is_unsendable_file` TINYINT(1) DEFAULT 0 NOT NULL,
データベースのtrue/falseで管理できるカラム名で否定語を使うのは良くないです。
修正しましょう

2020-07-13 02:50 UTC, shiraosa commented
以下を修正しました。

- 物理名is_unsendable_fileをis_sendable_fileに修正しました。またデフォルト値を１にしました。

2020-07-13 03:52 UTC, piasoratech requested changes
修正内容はOKです！
~から始まるxlsxファイルは一時ファイルなので、削除しておきましょう。

2020-07-13 04:13 UTC, shiraosa commented
一時ファイル削除しました

2020-07-13 04:16 UTC, piasoratech approved these changes
OKです！
次に進みましょう！

2020-07-13 04:48 UTC, merged