DB課題3の001~005の提出になります
shiraosa/quelcode-db pull request #4
Opened 2020-07-14 05:16 UTC by shiraosa

DB課題3の001~005の提出になります。レビューよろしくお願いします

やったこと

- 001~005のSQL文の作成

- http://localhost:10081/でSQL文をインポート

- インポート後にSELECT文を実行したキャプチャを添付

2020-07-14 06:31 UTC, Yuzunoha commented
- [ ] db-003 ... スクリーンショットのレコードの表示件数が足りないので、行数を増やしてとりなおしてください
- [ ] db-005 ... 課題は8レコードですが7レコードしか登録されていないようなので確認してください

2020-07-14 06:48 UTC, shiraosa commented
表示行数を増やしてスクリーンショットをとりなおしました。
>  db-003 ... スクリーンショットのレコードの表示件数が足りないので、行数を増やしてスクリーンショットだけとりなおしてください


テーブルを空にして修正したをdb-005.sqlをインポートしなおしました。

> db-005 ... 課題は8レコードですが7レコードしか登録されていないようなので確認してください

2020-07-14 08:54 UTC, fjtawork commented
確認しました
001〜005までOKです！

次に行きましょう！

2020-07-16 03:37 UTC, shiraosa commented
DB課題3の006~010の提出になります。レビューよろしくお願いします

やったこと

- 006~010のSQL文の作成

- http://localhost:10081/でSQL文をインポート

- インポートを実行したキャプチャを添付

2020-07-16 03:41 UTC, shiraosa commented
DB課題3の006~010の提出になります。レビューよろしくお願いします

やったこと

- 006~010のSQL文の作成

- http://localhost:10081/でSQL文をインポート

- インポートを実行したキャプチャを添付

2020-07-16 07:03 UTC, himaru-jp requested changes

2020-07-16 07:03 UTC, himaru-jp commented on db/db-challenge3/db-007/db-007.sql
> +WHERE is_direct_chat = 1
要件をご確認ください
> 概要がダイレクトチャットで終わっている

2020-07-16 07:03 UTC, himaru-jp commented on db/db-challenge3/db-010/db-010.sql
> +SELECT users.name,chatrooms.room_name,latest_chats.created_at AS latest_created_at
要件を満たしていませんのでご確認ください。
削除されているユーザの投稿をのぞき、最新の投稿を表示するようにしてください。

2020-07-16 07:03 UTC, himaru-jp commented on db/db-challenge3/db-010/db-010.sql
> +ON chats.created_at = latest_chats.created_at
チャットが増えた場合、同時刻での投稿があり得るため、
チャットルームIDも結合条件に入れるとより確実な抽出ができます。

2020-07-16 08:05 UTC, shiraosa commented
以下を修正しました

- db-007.sqlのwhere句を部分一致に修正しました。

- db-010.sqlの結合条件にチャットルームIDを含め、where句で削除されたユーザーの投稿が出ないようにしました。

2020-07-17 03:35 UTC, Yuzunoha commented
課題 006-010 OKです！！次に進んでください！！

以下連絡事項

- 当PRの概要欄が
  >DB課題3の001~005の提出

  なので後で見返したときに001~014の提出とわかるようにしてください

- キャプチャ名は名前だけでどの課題のものか分かるようにしてください。
  課題010のキャプチャ名はリネームしておいてください。

2020-07-20 02:50 UTC, shiraosa commented
DB課題3の011~014の提出になります。レビューよろしくお願いします

やったこと

- 課題010のキャプチャ名のリネーム

- 011~014のSQL文の作成

- http://localhost:10081/でSQL文をインポート

- インポートを実行したキャプチャとselectとした結果のキャプチャを添付

2020-07-20 03:47 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-07-20 03:47 UTC, piasoratech commented on db/db-challenge3/db-011/db-011.sql
> +AND created_at <= '2020-04-26 11:30:00'
ここの日時表記が統一されていないので、統一してください。

2020-07-20 04:45 UTC, shiraosa commented
以下を修正しました。

- db-011の日時表記を統一しました。

- db-012.sqlの`chatrooms.is_deleted`の不要な`chatrooms`を無くしました。

2020-07-20 06:00 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-07-20 06:00 UTC, piasoratech commented on db/db-challenge3/db-011/db-011.sql
> +AND created_at <= '2020-04-26 11:30:00'
0埋めにするかしないかも統一してください。

2020-07-20 06:12 UTC, shiraosa commented
大変失礼しました。0埋めで日時表記を統一しました。

2020-07-20 06:17 UTC, piasoratech approved these changes
OKです！
お疲れ様でした！

2020-10-30 02:09 UTC, merged